version: 0.2

phases:
  install:
    runtime-versions:
      java: 8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package 
#  post_build:
#    commands:
#      - echo Build completed on `date`
#      - mvn package
artifacts:
  files:
    - target/aws-demo.jar
#    - appspec.yml
  discard-paths: yes